parameters:
    silex.silex_application.class: 'Silex\Application'

services:
    silex_application:
        class: '%silex.silex_application.class%'



#arguments: ['@jms_serializer', '@sigfacil.application_xml']
#calls:
 #           - [setSolicitacao, ["@sigfacil.solicitacao"]]